name: pyscreener

channels:
  - conda-forge
  - defaults

dependencies:
  - pdbfixer
  - pip
  - python=3.8
  - cudatoolkit=11.7
  - pytorch::pytorch-cuda=11.7
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - openbabel
  - openmm
  - pip:
    - colorama
    - configargparse
    - h5py
    - numpy
    - ray[default]==1.13.0
    - ray[tune]
    - rdkit
    - pandas
    - scikit_learn
    - scipy
    - tqdm
    - tensorflow
    - tensorflow-addons
    - pytorch-lightning
